// =============================================================================
// File        : tb_top.sv
// Description : Top-level testbench module
//
// This is the ONLY file with a `timescale directive per [TC2].
// Instantiates:
//   - Clock and reset generation
//   - DUT (ahb2apb_bridge)
//   - AHB and APB interfaces
//   - Virtual interface registration in config_db
//   - UVM test launch
//
// Derivation:
//   - Manifest: HCLK period=10ns, HRESETn active-low asserted 100ns
//   - IP-XACT: all DUT port names and widths
//   - Tool: Questa FSE, UVM 1.1d, +define+UVM_NO_DPI
//
// Confidence: HIGH for structure, MEDIUM for port connections.
//
// EDIT_REQUIRED: Every DUT port connection should be verified against
//   the actual RTL module declaration.  IP-XACT names may differ from RTL.
// =============================================================================

`timescale 1ns/1ps

module tb_top;

  import uvm_pkg::*;
  `include "uvm_macros.svh"

  // Import the project package — generated by the script
  import ahb2apb_bridge_pkg::*;

  // =========================================================================
  // Clock Generation
  //
  // HCLK: 10ns period (100MHz) per manifest.
  // Single clock domain — bridge uses HCLK for both AHB and APB.
  // Per [U8]: only tb_top generates clock.
  // =========================================================================
  logic HCLK;
  initial HCLK = 0;
  always #5 HCLK = ~HCLK;  // 5ns half-period = 10ns period

  // =========================================================================
  // Reset Generation
  //
  // HRESETn: active-low, asserted for 100ns per manifest.
  // Per IP-XACT: "All outputs deasserted. HREADY_OUT driven high after
  //   reset release."
  // Per [U8]: only tb_top generates reset.
  // =========================================================================
  logic HRESETn;
  initial begin
    HRESETn = 0;       // Assert reset at time 0
    #100;              // Hold for 100ns per manifest
    HRESETn = 1;       // Release reset
  end

  // =========================================================================
  // Interface Instantiation
  // =========================================================================
  ahb_mst_if ahb_if (.HCLK(HCLK), .HRESETn(HRESETn));
  apb_slv_if apb_if (.HCLK(HCLK), .HRESETn(HRESETn));

  // =========================================================================
  // DUT Instantiation
  //
  // Port connections derived from IP-XACT.
  // EDIT_REQUIRED: Verify each port name matches the RTL module declaration
  //   exactly.  IP-XACT names sometimes differ from actual RTL port names.
  //
  // EDIT_RECOMMENDED: If DUT has parameters, pass them here:
  //   #(.ADDR_WIDTH(32), .DATA_WIDTH(32), ...)
  // =========================================================================
  ahb2apb_bridge #(
    // EDIT_RECOMMENDED: Verify parameter names match RTL
    .ADDR_WIDTH   (32),
    .DATA_WIDTH   (32)
  ) dut (
    // ---- Clock and Reset ----
    .HCLK         (HCLK),                    // EDIT_REQUIRED: verify RTL port name
    .HRESETn      (HRESETn),                 // EDIT_REQUIRED: verify RTL port name

    // ---- AHB Slave Interface (DUT inputs from TB) ----
    .HADDR        (ahb_if.HADDR),            // EDIT_REQUIRED: verify RTL port name
    .HTRANS       (ahb_if.HTRANS),           // EDIT_REQUIRED: verify RTL port name
    .HWRITE       (ahb_if.HWRITE),           // EDIT_REQUIRED: verify RTL port name
    .HSIZE        (ahb_if.HSIZE),            // EDIT_REQUIRED: verify RTL port name
    .HBURST       (ahb_if.HBURST),           // EDIT_REQUIRED: verify RTL port name
    .HWDATA       (ahb_if.HWDATA),           // EDIT_REQUIRED: verify RTL port name
    .HSEL         (ahb_if.HSEL),             // EDIT_REQUIRED: verify RTL port name
    .HREADY_IN    (ahb_if.HREADY_IN),        // EDIT_REQUIRED: verify RTL port name

    // ---- AHB Slave Interface (DUT outputs to TB) ----
    .HRDATA       (ahb_if.HRDATA),           // EDIT_REQUIRED: verify RTL port name
    .HREADY_OUT   (ahb_if.HREADY_OUT),       // EDIT_REQUIRED: verify RTL port name
    .HRESP        (ahb_if.HRESP),            // EDIT_REQUIRED: verify RTL port name

    // ---- APB Master Interface (DUT outputs to TB) ----
    .PADDR        (apb_if.PADDR),            // EDIT_REQUIRED: verify RTL port name
    .PSEL         (apb_if.PSEL),             // EDIT_REQUIRED: verify RTL port name
    .PENABLE      (apb_if.PENABLE),          // EDIT_REQUIRED: verify RTL port name
    .PWRITE       (apb_if.PWRITE),           // EDIT_REQUIRED: verify RTL port name
    .PWDATA       (apb_if.PWDATA),           // EDIT_REQUIRED: verify RTL port name

    // ---- APB Master Interface (DUT inputs from TB) ----
    .PRDATA       (apb_if.PRDATA),           // EDIT_REQUIRED: verify RTL port name
    .PREADY       (apb_if.PREADY),           // EDIT_REQUIRED: verify RTL port name
    .PSLVERR      (apb_if.PSLVERR)           // EDIT_REQUIRED: verify RTL port name
  );

  // =========================================================================
  // Virtual Interface Registration
  //
  // Per [U1]: no modport suffix in config_db type.
  // Per [U2]: use null scope for set().
  // =========================================================================
  initial begin
    // Register AHB master interface — accessed by ahb_mst driver and monitor
    uvm_config_db#(virtual ahb_mst_if)::set(null, "uvm_test_top.env.ahb_agt.*", "vif", ahb_if);

    // Register APB slave interface — accessed by apb_slv driver and monitor
    uvm_config_db#(virtual apb_slv_if)::set(null, "uvm_test_top.env.apb_agt.*", "vif", apb_if);
  end

  // =========================================================================
  // UVM Test Launch
  //
  // Test name selected via +UVM_TESTNAME on command line.
  // =========================================================================
  initial begin
    run_test();
  end

  // =========================================================================
  // Simulation timeout safety net
  //
  // Prevents infinite simulation if something hangs.
  // 10,000ns should be plenty for 5 transactions at 10ns period.
  //
  // EDIT_OPTIONAL: Increase if your DUT has long latencies.
  // =========================================================================
  initial begin
    #10_000;
    `uvm_fatal("TIMEOUT", "Simulation timed out after 10,000ns")
  end

endmodule